### ISSUE TITLE
getting Only omelet when choosing a random option

### ISSUE THREAD

**Issue by Tarekb93** [WebAhead6/Recipinator#18]
although Basheer did change the code (it changed only for **search option** > **not random option)**

**Comment by baderfahoum17** [comment]
due to limitation to 5000 api calls, we replicated the behaviour of the actual api
which is pretty smart from our part :) 
i think that most won't think of this clever solution when facing this kind of issue for using an api that needs to paid for

read the code next time before submitting such issues
